-- MySQL Script generated by MySQL Workbench
-- Sat Aug 26 10:38:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Convention2017
-- -----------------------------------------------------
-- Convention 2017 Schema
-- 

-- -----------------------------------------------------
-- Schema Convention2017
--
-- Convention 2017 Schema
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Convention2017` DEFAULT CHARACTER SET utf8 ;
USE `Convention2017` ;

-- -----------------------------------------------------
-- Table `Convention2017`.`Registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Convention2017`.`Registration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `familyname` VARCHAR(45) NULL,
  `cost` INT NOT NULL DEFAULT 120,
  `paid` TINYINT NOT NULL DEFAULT 0,
  `address` VARCHAR(250) NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Convention2017`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Convention2017`.`Member` (
  `idRegistration` INT NOT NULL,
  `emailRegistration` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `child` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_Member_Registration_idx` (`idRegistration` ASC, `emailRegistration` ASC),
  CONSTRAINT `fk_Member_Registration`
    FOREIGN KEY (`idRegistration` , `emailRegistration`)
    REFERENCES `Convention2017`.`Registration` (`id` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Convention2017`.`Donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Convention2017`.`Donation` (
  `idRegistration` INT NOT NULL,
  `emailRegistration` VARCHAR(45) NOT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`idRegistration`, `emailRegistration`),
  CONSTRAINT `fk_Donation_Registration1`
    FOREIGN KEY (`idRegistration` , `emailRegistration`)
    REFERENCES `Convention2017`.`Registration` (`id` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
